export const RETRIEVE_DOCUMENTS = 'RETRIEVE_DOCUMENTS';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const OPEN_DOCUMENT = 'OPEN_DOCUMENT';
export const SAVE_DOCUMENT = 'SAVE_DOCUMENT';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';